<a href="https://colab.research.google.com/github/KyllianBeguin/Meteo_CTF/blob/main/Nettoyage.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
# https://github.com/KyllianBeguin/Meteo_CTF/

In [ ]:
df_raw = pd.read_excel("Climat.xlsx", sheet_name='SI -erreur')

/usr/local/lib/python3.7/dist-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

# Dataset processing
* Cut
* Unpivot

In [ ]:
df = df_raw.iloc[:, 3:] # Begin at the third column
colonnes = list(df.iloc[1,:]) # Extract month name
df = df.iloc[1:, :] # skip the month row and the line under
df.columns = colonnes # Change columns name
df = df.iloc[2:, :] # Skip the first two rows
df.reset_index(drop = True, inplace=True) # Reset index
df = df.iloc[:31, :] # Skip the garbage rows
df = df.melt() # Unpivot the table
df.dropna(inplace = True)
df.reset_index(drop = True, inplace=True)
df.columns = ["month", "temperature_C"]


day = []
for i in colonnes:
  nb_day = len(df[df["month"] == i])
  month_days = ["D"+str(i+1) for i in range(len(df[df["month"] == i]))]
  day = day + month_days

df["day"] = day

df.head(5)
df.tail(5)

        month temperature_C  day
360  décembre            -7  D27
361  décembre            -8  D28
362  décembre            -6  D29
363  décembre            -7  D30
364  décembre            -5  D31

In [ ]:
# Bonjour

prendre x valeurs en dessous et x valeurs au dessus
moyenne de la liste de valeur

Exemple : [2,3,5, X, 6,8,4]  
Moyenne (sans X) = (2+3+5+6+8+4)/

In [ ]:
#For each NaN value, we replace it w/ a None
for i in df["temperature_C"]:
  print(i,"is Nan")

-5 is Nan
-6 is Nan
-5 is Nan
-3 is Nan
-6 is Nan
-11 is Nan
-6 is Nan
-8 is Nan
-11 is Nan
-8 is Nan
-8 is Nan
-8 is Nan
-8 is Nan
-10 is Nan
-10 is Nan
-9 is Nan
-6 is Nan
-6 is Nan
-4 is Nan
-8 is Nan
-9 is Nan
-14 is Nan
-15 is Nan
-17 is Nan
-19 is Nan
-23 is Nan
-8 is Nan
-9 is Nan
-5 is Nan
-6 is Nan
-7 is Nan
-7 is Nan
-6 is Nan
-5 is Nan
-6 is Nan
-8 is Nan
-9 is Nan
5 is Nan
-11 is Nan
-12 is Nan
-9 is Nan
-6 is Nan
-5 is Nan
-4 is Nan
1 is Nan
3 is Nan
-9 is Nan
-6 is Nan
-6 is Nan
-4 is Nan
2 is Nan
3 is Nan
1 is Nan
-3 is Nan
-4 is Nan
-6 is Nan
-8 is Nan
-8 is Nan
-11 is Nan
-7 is Nan
-8 is Nan
-5 is Nan
-3 is Nan
-2 is Nan
1 is Nan
2 is Nan
1 is Nan
1 is Nan
2 is Nan
1 is Nan
3 is Nan
5 is Nan
5 is Nan
7 is Nan
0xFFFF is Nan
2 is Nan
-1 is Nan
-2 is Nan
-1 is Nan
0 is Nan
1 is Nan
2 is Nan
3 is Nan
4 is Nan
3 is Nan
4 is Nan
5 is Nan
5 is Nan
3 is Nan
3 is Nan
2 is Nan
3 is Nan
4 is Nan
6 is Nan
4 is Nan
5 is Nan
4 is Nan
6 is Nan
7 is Nan
7 is Nan
8 is Nan
8 is Nan
9 is Nan
10 is Nan
8 is Nan
8 is Nan
9 is Nan
11 is Nan
10 is Nan
11 is Nan
12 is Nan
9 is Nan
7 is Nan
8 is Nan
8 is Nan
6 is Nan
9 is Nan
11 is Nan
14 is Nan
16 is Nan
12 is Nan
14 is Nan
15 is Nan
16 is Nan
13 is Nan
12 is Nan
8 is Nan
7 is Nan
6 is Nan
5 is Nan
5 is Nan
6 is Nan
8 is Nan
10 is Nan
12 is Nan
13 is Nan
14 is Nan
13 is Nan
15 is Nan
15 is Nan
15 is Nan
18 is Nan
18 is Nan
16 is Nan
15 is Nan
16 is Nan
16 is Nan
17 is Nan
16 is Nan
17 is Nan
17 is Nan
17 is Nan
16 is Nan
17 is Nan
14 is Nan
15 is Nan
17 is Nan
17 is Nan
15 is Nan
14 is Nan
Cloudy is Nan
14 is Nan
13 is Nan
11 is Nan
14 is Nan
15 is Nan
15 is Nan
15 is Nan
17 is Nan
16 is Nan
19 is Nan
20 is Nan
19 is Nan
20 is Nan
22 is Nan
22 is Nan
21 is Nan
22 is Nan
21 is Nan
21 is Nan
17 is Nan
20 is Nan
20 is Nan
17 is Nan
18 is Nan
17 is Nan
17 is Nan
16 is Nan
17 is Nan
17 is Nan
15 is Nan
15 is Nan
16 is Nan
16 is Nan
13 is Nan
14 is Nan
-6 is Nan
15 is Nan
15 is Nan
15 is Nan
17 is Nan
18 is Nan
19 is Nan
0xFFFF is Nan
24 is Nan
23 is Nan
26 is Nan
26 is Nan
21 is Nan
22 is Nan
23 is Nan
21 is Nan
20 is Nan
19 is Nan
19 is Nan
18 is Nan
17 is Nan
18 is Nan
16 is Nan
17 is Nan
15 is Nan
14 is Nan
14 is Nan
15 is Nan
15 is Nan
15 is Nan
48 is Nan
18 is Nan
19 is Nan
21 is Nan
24 is Nan
21 is Nan
21 is Nan
26 is Nan
17 is Nan
18 is Nan
17 is Nan
17 is Nan
16 is Nan
17 is Nan
17 is Nan
18 is Nan
17 is Nan
16 is Nan
14 is Nan
15 is Nan
13 is Nan
12 is Nan
10 is Nan
12 is Nan
11 is Nan
11 is Nan
12 is Nan
10 is Nan
10 is Nan
9 is Nan
9 is Nan
10 is Nan
11 is Nan
10 is Nan
10 is Nan
9 is Nan
11 is Nan
12 is Nan
12 is Nan
10 is Nan
11 is Nan
10 is Nan
9 is Nan
6 is Nan
7 is Nan
7 is Nan
6 is Nan
6 is Nan
2 is Nan
3 is Nan
4 is Nan
3 is Nan
2 is Nan
4 is Nan
0xFFFF is Nan
3 is Nan
4 is Nan
2 is Nan
1 is Nan
3 is Nan
3 is Nan
3 is Nan
1 is Nan
4 is Nan
6 is Nan
6 is Nan
6 is Nan
7 is Nan
7 is Nan
6 is Nan
6 is Nan
6 is Nan
4 is Nan
3 is Nan
3 is Nan
4 is Nan
2 is Nan
1 is Nan
0 is Nan
1 is Nan
2 is Nan
3 is Nan
4 is Nan
3 is Nan
4 is Nan
5 is Nan
5 is Nan
-1 is Nan
-2 is Nan
-1 is Nan
-7 is Nan
-8 is Nan
-5 is Nan
-3 is Nan
-2 is Nan
1 is Nan
2 is Nan
1 is Nan
0 is Nan
0 is Nan
1 is Nan
3 is Nan
5 is Nan
-2 is Nan
-3 is Nan
-6 is Nan
-6 is Nan
-4 is Nan
-6 is Nan
-4 is Nan
-8 is Nan
-9 is Nan
-9 is Nan
-9 is Nan
-8 is Nan
-4 is Nan
-3 is Nan
-8 is Nan
-9 is Nan
-5 is Nan
-6 is Nan
-7 is Nan
-11 is Nan
-6 is Nan
-8 is Nan
-11 is Nan
-8 is Nan
-8 is Nan
-33 is Nan
-6 is Nan
-8 is Nan
-9 is Nan
-5 is Nan
-6 is Nan
-7 is Nan
-8 is Nan
-6 is Nan
-7 is Nan
-5 is Nan